name: Lint

on:
  workflow_dispatch:
  push:
    paths:
      - '*.py'
    branches:
      main
  pull_request:
    paths:
      - '*.py'
    branches:
      main

jobs:
  flake8_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: |
          flake8
