name: Code Testing

on:
  workflow_dispatch:
  pull_request:
    branches:
      main
  push:
    branches:
      main

jobs:
  pytest:
    if: github.repository == 'BlauGroup/NanoParticleTools'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[full,test]
          pip install pytest-cov
      - name: Run tests
        run: |
          pytest --cov=src --cov-report=term-missing
        shell:
          bash
